config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i(new create)
  resources :sessions, only: %i(new create destroy)
  resources :password_resets, only: %i(new create show edit update)
  root "static_pages#home"

  namespace :app do
    resources :headquarters, only: %i(index create show update) do
      resources :projects, only: %i(new create)
      resources :hq_memberships, only: %i(index create)
    end

    resources :projects, only: %i(show) do
      resources :project_memberships, only: %i(index)
    end

    resources :hq_memberships, only: %i(update destroy)
    resources :hq_invitations, only: %i(show update destroy)
  end
end

app/models/concerns/hq_membership/filterable.rb
class HqMembership
  module Filterable
    extend ActiveSupport::Concern

    module ClassMethods
      def filter_by_role(role)
        return self.all unless role.present?

        if role.downcase == "pending"
          pending_members
        else
          members_with_role(role.downcase)
        end
      end
    end
  end
end

app/models/hq_membership.rb
class HqMembership < ApplicationRecord
  include Filterable

  belongs_to :user
  belongs_to :headquarter

  scope :pending_members, -> { where(invitation_accepted: false) }
  scope :members_with_role, ->(role) { where(role: role) }

  enum role: { member: "member", owner: "owner" }

  validates_uniqueness_of :user, case_sensitive: false, scope: :headquarter_id, message: "is already on the HQ"

  delegate :name, :email, :headquarter_owner?, to: :user
end

app/models/tombstone/hq_membership.rb
class Tombstone::HqMembership
  def initialize(hq_membership:, current_user:)
    @hq_membership  = hq_membership
    @current_user   = current_user
  end

  def needs_partner_owner?
    lone_owner? && current_user_is_headquarter_owner? && is_current_user?
  end

  private
  attr_reader :hq_membership, :current_user

  def current_user_is_headquarter_owner?
    current_user.headquarter_owner?(hq_membership.headquarter)
  end

  def is_current_user?
    current_user == hq_membership.user
  end

  def lone_owner?
    total_owners == 1
  end

  def total_owners
    hq_membership.headquarter.total_owners
  end
end

app/controllers/app/hq_memberships_controller.rb
class App::HqMembershipsController < App::ApplicationController
  def index
    @headquarter    = Headquarter.find(params[:headquarter_id])
    @hq_memberships = policy_scope(@headquarter, policy_scope_class: HqMembershipPolicy::Scope).
      filter_by_role(params[:role])
  end

  def create
    headquarter = Headquarter.find(params[:headquarter_id])
    authorize headquarter, policy_class: HqMembershipPolicy

    member = Invitation::Headquarter.new(
      headquarter: headquarter,
      email: params[:email],
      name: params[:name],
      role: params[:role],
      current_user: current_user
    )

    if member.save
      redirect_to app_headquarter_hq_memberships_url(headquarter), success: "Invitation sent to #{member.email}"
    else
      render json: { errors: member.errors }, status: :bad_request
    end
  end

  def update
    hq_membership = HqMembership.find(params[:id])
    authorize hq_membership, :roller?

    if hq_membership.owner?
      hq_membership.member!
      flash[:success] = "Demoted #{hq_membership.name} to member"
    else
      hq_membership.owner!
      flash[:success] =  "Promoted #{hq_membership.name} to owner"
    end
    redirect_back fallback_location: app_headquarter_hq_memberships_url(hq_membership.headquarter)
  end

  def destroy
    hq_membership = HqMembership.find(params[:id])
    authorize hq_membership

    persisted_owner = Tombstone::HqMembership.new(hq_membership: hq_membership, current_user: current_user)
    if persisted_owner.needs_partner_owner?
      redirect_back fallback_location: app_headquarter_hq_memberships_url(hq_membership.headquarter)
      flash[:alert] = "You are the only owner in the HQ, promote someone before you leave"
      return
    end

    hq_membership.destroy
    if current_user == hq_membership.user
      redirect_to app_headquarters_url, success: "Exited for good reasons"
    else
      flash[:success] = "Removed #{hq_membership.name} for good reasons"
      redirect_back fallback_location: app_headquarter_hq_memberships_url(hq_membership.headquarter)
    end
  end
end

app/views/app/hq_memberships/_demote_action.html.erb
<div data-controller="card" data-action="click@window->card#onOutsideClick" data-card-toggle-class="card__option--hidden">
  <button data-target="card.initiator" data-action="click->card#showConfirmation" class="card__option-item">
    <%= embed_svg "trending-down-solid", size: 20 %>
    Demote to member
  </button>
  <div data-target="card.confirm" class="card__option-item card__option--hidden">
    <%= embed_svg "trending-down-solid", size: 20 %>
    <%= form_with url: app_hq_membership_url(member), method: :patch do |f| %>
      <%= f.submit "Demote", class: "card__option-confirm card__option-confirm--danger" %>
    <% end %>
    <span class="mx-2">|</span>
    <button data-action="click->card#hideConfirmation" class="card__option-confirm">
      Cancel
    </button>
  </div>
</div>

app/views/app/hq_memberships/_exit_action.html.erb
<div data-controller="card" data-action="click@window->card#onOutsideClick" data-card-toggle-class="card__option--hidden">
  <button data-target="card.initiator" data-action="click->card#showConfirmation" class="card__option-item">
    <%= embed_svg "trending-down-solid", size: 20 %>
    Exit from HQ
  </button>
  <div data-target="card.confirm" class="card__option-item card__option--hidden">
    <%= embed_svg "trending-down-solid", size: 20 %>
    <%= form_with url: app_hq_membership_url(member), method: :delete do |f| %>
      <%= f.submit "Exit", class: "card__option-confirm card__option-confirm--danger" %>
    <% end %>
    <span class="mx-2">|</span>
    <button data-action="click->card#hideConfirmation" class="card__option-confirm">
      Cancel
    </button>
  </div>
</div>

app/views/app/hq_memberships/_invite_form.html.erb
<%= render Containers::ModalComponent.new(title: "Invite colleague to HQ") do |component| %>
  <% component.with(:body) do %>
    <%= form_with url: app_headquarter_hq_memberships_url(@headquarter),
      data: {
        controller: "form",
        action: "ajax:error->form#onError"
      },
      class: "form" do |f|
    %>
      <div class="box--restrict">
        <div class="box__content--with-footer box--overflow">
          <section>
            <div class="form__group">
              <%= f.label :name, "Full name", class: "form__label" %>
              <%= f.text_field :name, class: "input", autocomplete: "off", required: true %>
              <%= render Forms::ErrorDisplayComponent.new(error_type: "name") %>
            </div>
            <div class="form__group">
              <%= f.label :email, "Email address", class: "form__label" %>
              <%= f.email_field :email, class: "input", autocomplete: "off", required: true %>
              <%= render Forms::ErrorDisplayComponent.new(error_type: "email") %>
            </div>
            <% if current_user.headquarter_owner?(@headquarter) %>
              <div class="form__group">
                <label for="#" class="form__label">Role</label>
                <div class="radio__group-custom">
                  <div class="radio__wrapper">
                    <%= label_tag "", class: "radio__custom-label" do %>
                      <%= f.radio_button :role, :owner, class: "input__radio" %>
                      <p class="input__radio-content">
                        <span class="input__radio-name">Owner</span>
                        <span class="input__radio-description">can manage the entire account, billings, etc</span>
                      </p>
                    <% end %>
                  </div>
                  <div class="radio__wrapper">
                    <%= label_tag "", class: "radio__custom-label" do %>
                      <%= f.radio_button :role, :member, checked: true, class: "input__radio" %>
                      <p class="input__radio-content">
                        <span class="input__radio-name">Member</span>
                        <span class="input__radio-description">can manage project, changelogs, etc</span>
                      </p>
                    <% end %>
                  </div>
                </div>
              </div>
            <% else %>
              <p class="font--description text-sm mt-2">
                <span class="font-semibold">Note:</span>
                Member roles can be specified only by the owners of the HQ.
              </p>
            <% end %>
          </section>
        </div>
      </div>
      <div class="box__footer box__footer--right">
        <button type="button" data-action="click->modal#hideModal" class="btn btn--outlined">
          Cancel
        </button>
        <%= f.submit "Send invite", class: "btn btn--primary" %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/app/hq_memberships/_member_card.html.erb
<%= render Cards::SplitModelComponent.new(
    title: member.name,
    show_actions: current_user.headquarter_owner?(member.headquarter) || current_user == member.user
  ) do |component|
%>
  <% component.with(:left_body) do %>
    <div class="avatar__container">
      <img src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" class="avatar avatar--lg avatar--rounded">
    </div>
  <% end %>
  <% component.with(:right_body) do %>
    <div class="card__description truncate">
      <a href="mailto:<%= member.email %>" class="link link--primary link--weighted truncate">
        <%= member.email %>
      </a>
      <% if member.join_date %>
        <p class="font--support">
          Good vibes since <%= format_date(member.join_date) %>
        </p>
      <% end %>
    </div>
    <% unless member.invitation_accepted? %>
      <div class="ml-auto">
        <%= render BadgeComponent.new(title: "Pending", label: "Invite pending", type: "warning") %>
      </div>
    <% end %>
  <% end %>
  <% component.with(:actions) do %>
    <% if current_user == member.user %>
      <%= render "app/hq_memberships/exit_action", member: member %>
    <% else %>
      <% if member.headquarter_owner?(member.headquarter) %>
        <%= render "app/hq_memberships/demote_action", member: member %>
      <% else %>
        <%= render "app/hq_memberships/promote_action", member: member %>
      <% end %>
      <%= render "app/hq_memberships/remove_action", member: member %>
    <% end %>
  <% end %>
<% end %>

app/views/app/hq_memberships/_promote_action.html.erb
<div data-controller="card" data-action="click@window->card#onOutsideClick" data-card-toggle-class="card__option--hidden">
  <button data-target="card.initiator" data-action="click->card#showConfirmation" class="card__option-item">
    <%= embed_svg "trending-up-solid", size: 20 %>
    Promote to owner
  </button>
  <div data-target="card.confirm" class="card__option-item card__option--hidden">
    <%= embed_svg "trending-up-solid", size: 20 %>
    <%= form_with url: app_hq_membership_url(member), method: :patch do |f| %>
      <%= f.submit "Promote", class: "card__option-confirm card__option-confirm--primary" %>
    <% end %>
    <span class="mx-2">|</span>
    <button data-action="click->card#hideConfirmation" class="card__option-confirm">
      Cancel
    </button>
  </div>
</div>

app/views/app/hq_memberships/_remove_action.html.erb
<div data-controller="card" data-action="click@window->card#onOutsideClick" data-card-toggle-class="card__option--hidden">
  <button data-target="card.initiator" data-action="click->card#showConfirmation" class="card__option-item">
    <%= embed_svg "trash-solid", size: 20 %>
    Remove from HQ
  </button>
  <div data-target="card.confirm" class="card__option-item card__option--hidden">
    <%= embed_svg "trash-solid", size: 20 %>
    <%= form_with url: app_hq_membership_url(member), method: :delete do |f| %>
      <%= f.submit "Remove", class: "card__option-confirm card__option-confirm--danger" %>
    <% end %>
    <span class="mx-2">|</span>
    <button data-action="click->card#hideConfirmation" class="card__option-confirm">
      Cancel
    </button>
  </div>
</div>

app/views/app/hq_memberships/_tab.html.erb
<%= render TabComponent.new(
    links: [
      {
        name: "All",
        url: app_headquarter_hq_memberships_url(@headquarter.id)
      },
      {
        name: "Owners",
        url: request.query_parameters.merge({ role: "owner" })
      },
      {
        name: "Members",
        url: request.query_parameters.merge({ role: "member" })
      },
      {
        name: "Pending",
        url: request.query_parameters.merge({ role: "pending" })
      }
    ]
  )
%>

app/views/app/hq_memberships/index.html.erb
<div class="container container--sm">
  <%= render Headers::ActionableComponent.new(title: "HQ members") do |component| %>
    <% component.with(:actioner) do %>
      <div data-controller="modal">
        <button data-target="modal.opener" data-action="click->modal#showModal" class="btn btn__pill">
          <%= embed_svg "plus-solid", size: 20, class: "btn__pill__icon btn__pill__icon--left" %>
          Invite colleague
        </button>
        <%= render "invite_form" %>
      </div>
    <% end %>
  <% end %>
  <div class="actionable__content">
    <%= render "tab" %>
    <div class="grid__three_centered mt-4">
      <% @hq_memberships.each do |member| %>
        <%= render "member_card", member: member %>
      <% end %>
    </div>
  </div>
</div>