config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i(new create)
  resources :sessions, only: %i(new create destroy)
  resources :password_resets, only: %i(new create show edit update)
  root "static_pages#home"

  namespace :app do
    resources :headquarters, only: %i(index create show update) do
      resources :projects, only: %i(new create)
      resources :hq_memberships, only: %i(index create)
    end

    resources :projects, only: %i(show) do
      resources :project_memberships, only: %i(index)
    end

    resources :hq_memberships, only: %i(update destroy)
    resources :hq_invitations, only: %i(show update destroy)
  end
end

app/models/concerns/user/headquarter_tenant.rb
class User
  module HeadquarterTenant
    def headquarter_owner?(headquarter)
      find_headquarter_membership(headquarter).owner?
    end

    def headquarter_invite_accepted?(headquarter)
      find_headquarter_membership(headquarter).invitation_accepted?
    end

    def headquarter_invite_pending?(headquarter)
      !find_headquarter_membership(headquarter).invitation_accepted?
    end

    def has_headquarter_membership?(headquarter)
      hq_memberships.exists?(headquarter_id: headquarter.id)
    end

    def find_headquarter_membership(headquarter)
      hq_memberships.find_by(headquarter_id: headquarter.id)
    end
  end
end

app/models/concerns/user/password_reset.rb
class User
  module PasswordReset
    def password_reset_token_expired?
      self.password_reset_sent_at < 2.hours.ago
    end

    def reset_password_reset_fields
      self.password_reset_sent_at = nil
      self.password_reset_token   = nil
      self.save!
    end

    def set_password_reset_fields
      generate_token(:password_reset_token)
      self.password_reset_sent_at = Time.zone.now
      self.save!
    end
  end
end

app/models/concerns/user/project_tenant.rb
class User
  module ProjectTenant
    def has_project_membership?(project)
      project_memberships.exists?(project_id: project.id)
    end

    def project_invite_accepted?(project)
      find_project_membership(project).invitation_accepted?
    end

    def project_invite_pending?(project)
      !find_project_membership(project).invitation_accepted?
    end

    def find_project_membership(project)
      project_memberships.find_by(project_id: project.id)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include HeadquarterTenant
  include PasswordReset
  include ProjectTenant

  has_many :hq_memberships
  has_many :headquarters, through: :hq_memberships
  has_many :project_memberships
  has_many :projects, through: :project_memberships

  has_secure_password

  before_create :generate_auth_token
  before_save :normalize_email

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  MIN_PASSWORD_LENGTH = 6 # used by password reset

  validates_presence_of :email, :name
  validates_uniqueness_of :email, case_sensitive: false
  validates_length_of :email, :name, maximum: 255
  validates_format_of :email, with: VALID_EMAIL_REGEX
  validates_length_of :password, minimum: MIN_PASSWORD_LENGTH, allow_blank: true

  private
  def generate_auth_token
    generate_token(:auth_token)
  end

  def normalize_email
    self.email = email.downcase
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)

    if user.save
      login(user)
      redirect_to root_url
    else
      render json: { errors: user.errors }, status: :bad_request
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/views/users/_form.html.erb
<%= form_with model: model,
  data: {
    controller: "form",
    action: "ajax:error->form#onError"
  },
  html: { class: "form" } do |f|
%>
  <section>
    <div class="form__group">
      <%= f.label :name, class: "form__label" %>
      <%= f.text_field :name, class: "input", required: true %>
      <%= render Forms::ErrorDisplayComponent.new(error_type: "name") %>
    </div>

    <div class="form__group">
      <%= f.label :email, "Email address", class: "form__label" %>
      <%= f.email_field :email, class: "input", required: true %>
      <%= render Forms::ErrorDisplayComponent.new(error_type: "email") %>
    </div>

    <div class="form__group">
      <div class="form__hint-container">
        <%= f.label :password, class: "form__label" %>
        <p class="form__hint">(optional)</p>
      </div>
      <%= f.password_field :password, class: "input", required: true %>
      <%= render Forms::ErrorDisplayComponent.new(error_type: "password") %>
    </div>
  </section>

  <p class="form__tos">
    By signing up, you agree to the <a href="#" class="link link--dark link--weighted">terms and conditions</a>.
  </p>

  <section class="form__btn-group">
    <%= f.submit "Join Applog", class: "btn btn--primary btn--block btn--graphik" %>
  </section>
<% end %>

app/views/users/new.html.erb
<%= render Containers::FocussedComponent.new(title: "Get a free trial for 14 days") do |component| %>
  <% component.with(:body) do %>
    <%= render "form", model: @user %>
  <% end %>

  <% component.with(:footer) do %>
    <p class="focus__footer-text">
      Already have an account?
      <%= link_to "Sign in", new_session_url, class: "link link--primary link--weighted" %>
    </p>
  <% end %>
<% end %>