config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i(new create)
  resources :sessions, only: %i(new create destroy)
  resources :password_resets, only: %i(new create show edit update)
  root "static_pages#home"

  namespace :app do
    resources :headquarters, only: %i(index create show update) do
      resources :projects, only: %i(new create)
      resources :hq_memberships, only: %i(index create)
    end

    resources :projects, only: %i(show) do
      resources :project_memberships, only: %i(index)
    end

    resources :hq_memberships, only: %i(update destroy)
    resources :hq_invitations, only: %i(show update destroy)
  end
end

app/controllers/app/hq_invitations_controller.rb
class App::HqInvitationsController < App::ApplicationController
  layout "slate", only: %i(show)

  def show
    @hq_membership = HqMembership.find(params[:id])
    authorize @hq_membership
  end

  def update
    hq_membership = HqMembership.find(params[:id])
    authorize hq_membership

    if hq_membership.update(join_date: Time.zone.now, invitation_accepted: true)
      redirect_to app_headquarter_url(hq_membership.headquarter), success: "Yay! You're now part of the HQ"
    end
  end

  def destroy
    hq_membership = HqMembership.find(params[:id])
    authorize hq_membership

    if hq_membership.destroy
      redirect_to app_headquarters_url, success: "You have declined the invitation"
    end
  end
end

app/views/app/hq_invitations/show.html.erb
<%= render Containers::FocussedComponent.new(title: "You have an invitation to #{@hq_membership.headquarter.name}") do |component| %>
  <% component.with(:body) do %>
    <%= embed_svg "team", class: "mx-auto" %>
    <p class="font--description mt-7">
      You can accept the invitation by clicking on the accept
      button or decline it by clicking on the decline button.
    </p>
    <div class="btn__group--col-reverse btn__group--col-reverse--fw mt-5">
      <%= form_with url: app_hq_invitation_url(@hq_membership), method: :delete do |f| %>
        <%= f.submit "Decline invitation", class: "btn btn--danger btn--minimal btn--block btn--rounded" %>
      <% end %>
      <%= form_with url: app_hq_invitation_url(@hq_membership), method: :patch do |f| %>
        <%= f.submit "Accept invitation", class: "btn btn--primary btn--block btn--rounded" %>
      <% end %>
    </div>
  <% end %>

  <% component.with(:footer) do %>
    <p class="focus__footer-text">
      Nevermind,
      <%= link_to "I'll do it later", app_headquarters_url, class: "link link--primary link--weighted" %>
    </p>
  <% end %>
<% end %>